### ISSUE TITLE
res.send *after* res.json?

### ISSUE THREAD

**Issue by rudimk** [harleenkr/expressEndpoint#1]
https://github.com/harleenkr/expressEndpoint/blob/161b086b46d001188b892f35dc5fd0e81263ea49/controllers.js#L14

Not sure why you're using `res.send` after `res.json` in the controller. Could you tell me more about this?

**Comment by harleenkr** [comment]
@rudimk I was just testing it initially with some hardcoded data that's why use res.send(). Removing it. Fixed now.

**Comment by rudimk** [comment]
Lovely!
